spring.application.name=spring-ai
# Force servlet web application type to avoid reactive-server error
spring.main.web-application-type=servlet
spring.threads.virtual.enabled=true

# Ollama Configuration
spring.ai.model.chat=ollama
spring.ai.model.embedding=ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=qwen3:4b
spring.ai.ollama.chat.options.temperature=1
spring.ai.ollama.embedding.options.model=nomic-embed-text

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_1}
spring.data.mongodb.database=astrobiblia
spring.ai.vectorstore.mongodb.index-name=vector_index
spring.ai.vectorstore.mongodb.collection-name=vector_store
spring.ai.vectorstore.mongodb.initialize-schema=true