### Ingest Test - Astronomy Message El universo
http://localhost:8080/vector/ingest?message=El%20universo%20es%20inmenso%20y%20está%20lleno%20de%20misterios.%20Desde%20las%20estrellas%20hasta%20los%20agujeros%20negros,%20cada%20elemento%20tiene%20su%20propia%20historia%20y%20significado.%20La%20exploración%20del%20espacio%20nos%20ha%20permitido%20descubrir%20nuevos%20mundos%20y%20comprender%20mejor%20nuestro%20lugar%20en%20el%20cosmos.

### Ingest Test - Astronomy Message La misión Nostromo
http://localhost:8080/vector/ingest?message=La%20misión%20Nostromo%20fue%20un%20proyecto%20importante%20para%20la%20exploración%20espacial.%20Su%20objetivo%20principal%20era%20estudiar%20los%20asteroides%20y%20otros%20objetos%20cercanos%20a%20la%20Tierra,%20proporcionando%20datos%20valiosos%20para%20la%20ciencia%20y%20la%20seguridad%20planetaria.