### To Rag

### Ask Me recent questions
http://localhost:8080/rag/ama?prompt=3Iatlas

### Ask Me Anything from Local data
http://localhost:8080/rag/ama/local?prompt=3Iatlas

### Ask Me Anything from web knowledge base
http://localhost:8080/rag/ama/web?prompt=3I/ATLAS